/* Auto-generated by genmsg_cpp for file /home/human/ros_workspace/kinect_follower/msg/MoveState.msg */
#ifndef KINECT_FOLLOWER_MESSAGE_MOVESTATE_H
#define KINECT_FOLLOWER_MESSAGE_MOVESTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace kinect_follower
{
template <class ContainerAllocator>
struct MoveState_ {
  typedef MoveState_<ContainerAllocator> Type;

  MoveState_()
  : moving(false)
  {
  }

  MoveState_(const ContainerAllocator& _alloc)
  : moving(false)
  {
  }

  typedef uint8_t _moving_type;
  uint8_t moving;


  typedef boost::shared_ptr< ::kinect_follower::MoveState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinect_follower::MoveState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MoveState
typedef  ::kinect_follower::MoveState_<std::allocator<void> > MoveState;

typedef boost::shared_ptr< ::kinect_follower::MoveState> MoveStatePtr;
typedef boost::shared_ptr< ::kinect_follower::MoveState const> MoveStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kinect_follower::MoveState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kinect_follower::MoveState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kinect_follower

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kinect_follower::MoveState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kinect_follower::MoveState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kinect_follower::MoveState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9104f1a32b4fbf4d3c8c80d9b9493250";
  }

  static const char* value(const  ::kinect_follower::MoveState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9104f1a32b4fbf4dULL;
  static const uint64_t static_value2 = 0x3c8c80d9b9493250ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinect_follower::MoveState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kinect_follower/MoveState";
  }

  static const char* value(const  ::kinect_follower::MoveState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kinect_follower::MoveState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool moving\n\
\n\
";
  }

  static const char* value(const  ::kinect_follower::MoveState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::kinect_follower::MoveState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kinect_follower::MoveState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.moving);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MoveState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinect_follower::MoveState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kinect_follower::MoveState_<ContainerAllocator> & v) 
  {
    s << indent << "moving: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.moving);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KINECT_FOLLOWER_MESSAGE_MOVESTATE_H

