/* Auto-generated by genmsg_cpp for file /home/human/ros_workspace/ros_intro/msg/JoyAxis.msg */
#ifndef ROS_INTRO_MESSAGE_JOYAXIS_H
#define ROS_INTRO_MESSAGE_JOYAXIS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ros_intro
{
template <class ContainerAllocator>
struct JoyAxis_ {
  typedef JoyAxis_<ContainerAllocator> Type;

  JoyAxis_()
  : x(0.0)
  , y(0.0)
  {
  }

  JoyAxis_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  {
  }

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;


  typedef boost::shared_ptr< ::ros_intro::JoyAxis_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_intro::JoyAxis_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct JoyAxis
typedef  ::ros_intro::JoyAxis_<std::allocator<void> > JoyAxis;

typedef boost::shared_ptr< ::ros_intro::JoyAxis> JoyAxisPtr;
typedef boost::shared_ptr< ::ros_intro::JoyAxis const> JoyAxisConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ros_intro::JoyAxis_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ros_intro::JoyAxis_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ros_intro

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ros_intro::JoyAxis_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ros_intro::JoyAxis_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ros_intro::JoyAxis_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const  ::ros_intro::JoyAxis_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_intro::JoyAxis_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ros_intro/JoyAxis";
  }

  static const char* value(const  ::ros_intro::JoyAxis_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ros_intro::JoyAxis_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 x\n\
float32 y\n\
\n\
";
  }

  static const char* value(const  ::ros_intro::JoyAxis_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ros_intro::JoyAxis_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ros_intro::JoyAxis_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct JoyAxis_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_intro::JoyAxis_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ros_intro::JoyAxis_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROS_INTRO_MESSAGE_JOYAXIS_H

